### ISSUE TITLE
Some error after running npm start

### ISSUE THREAD

**Issue by p4tric** [petervn/MovieBrowserHaiNg#1]
Hi,

See screenshot below.

![image](https://user-images.githubusercontent.com/1955349/67449919-5fffea80-f64e-11e9-8f95-e794a1397e4e.png)

**Comment by petervn** [comment]
Hi @p4tric ,
I think ran many React Native projects on your Macbook, each project have its own configuration and that caused the issues.

Can you re-start your Macbook,
and try some commands below to clear cache
---
rm -rf node_modules/
rm -rf ~/Library/Caches/CocoaPods
delete ios/pod folder
delete ios/build folder
pod deintegrate   
watchman watch-del-all && rm -rf node_modules/ && npm cache clean && npm install && npm start -- --reset-cache.
---
And then re-run
1. npm install
cd ios :  pod install
cd ..
npm start
